### ISSUE TITLE
Volto support (REST API, Plone 5.2)

### ISSUE THREAD

**Issue by tisto** [collective/collective.embeddedpage#24]
- Write a serializer that does a request to the site under the "URL" attribute.
- Plone RESTAPI returns a "normal" result in the text field:

```
text: {
  "data": "<p>HTML CODE FROM THE EMBEDDED PAGE</p>",
  "content-type": "text/html",
  "encoding": "utf-8"
}
````

**Comment by rodfersou** [comment]
@tisto talking with @sneridagh he come up with the idea to just override the `text` attribute; this way don't need to do anything at the Volto land.

**Comment by tisto** [comment]
@rodfersou the attribute I pasted above is the text attribute:

````
text: {
  "data": "<p>HTML CODE FROM THE EMBEDDED PAGE</p>",
  "content-type": "text/html",
  "encoding": "utf-8"
}
````
