### ISSUE TITLE
Title is showen doubled when add embeddedpage

### ISSUE THREAD

**Issue by humboldtuni** [collective/collective.embeddedpage#42]
Please take out the 'Title' in schema, because there is already a 'plone.namefromtitle' behavior

**Comment by tisto** [comment]
The EmbeddedPage content type indeed defines title and description twice. Once in the interface/schema:

https://github.com/collective/collective.embeddedpage/blob/main/src/collective/embeddedpage/interfaces.py#L19

And via the Dublin core behavior:

https://github.com/collective/collective.embeddedpage/blob/main/src/collective/embeddedpage/profiles/default/types/EmbeddedPage.xml#L41

**Comment by tisto** [comment]
PR with the fix: https://github.com/collective/collective.embeddedpage/pull/43

**Comment by tisto** [comment]
@humboldtuni released with https://pypi.org/project/collective.embeddedpage/3.0.1/
