### ISSUE TITLE
Multilingual behavior for EmbeddedPage 

### ISSUE THREAD

**Issue by humboldtuni** [collective/collective.embeddedpage#44]
Would you please add behavior 'plone.app.multilingual.dx.interfaces.IDexterityTranslatable' to Embeddedpage?
Thank you!

**Comment by tisto** [comment]
@humboldtuni could you please elaborate why we would want to add this behavior? Content types are automatically translatable in Plone 5 if I am not mistaken. None of the content types in plone.app.contenttypes has this behavior enabled by default. Therefore I would prefer to follow the best practices for content types to not introduce a hard dependency of any kind here.

**Comment by humboldtuni** [comment]
This product ist not per default installed like those in plone.app.contenttypes. If it is installed afterwards (pam is already installed), the embeddedpage will not have translatible behavior automatically. Ofcourse I can switch it on extra per hand, but I think multilingual is a standard behavior and should be switch on automatically.
